### ISSUE TITLE
Process images

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/archives#5]
- Copy images (compressed, converted to jpeg) from s3://stanforddailyarchive to s3://stanforddailyarchive-new
- Copy mets/alto xml files from s3://stanforddailyarchive to s3://stanforddailyarchive-new
- Create an index.json file at the s3 bucket with an actual index -- which has a list of all days, months, and years that have articles (this is used to create the calendar / browse view).

- All files are at the root of s3://stanforddailyarchive-new

**Comment by hesyifei** [comment]
We should also copy the PDFs as people might want to download them.

**Comment by epicfaace** [comment]
Sure, but we should compress them too -- otherwise it might charge us a lot of money if people are downloading hundreds of megabytes of PDFs from us on a daily basis.
