### ISSUE TITLE
Duplicated content in each txt file

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/archives#7]
Such as https://github.com/TheStanfordDaily/archives-text/blob/355483e5c93efeac523a5f8ca22def146a702ec8/1896/02/05/MODSMD_ARTICLE5.article.txt

**Comment by epicfaace** [comment]
archives site page: https://archives.stanforddaily.com/1896/02/05?page=1#issue
METS: https://tiles.archives.stanforddaily.com/data.2013-dec/data/stanford/1896/02/05_01/Stanford_Daily_18960205_0001-METS.xml
ALTO: https://tiles.archives.stanforddaily.com/data.2013-dec/data/stanford/1896/02/05_01/Stanford_Daily-ALTO/Stanford_Daily_18960205_0001_ALTO0001.xml

**Comment by ufxela** [comment]
fixed in #11
